name: ci

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'demo/**'
      - 'img/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
